version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: "on-failure:5"
    ports:
      - "4242:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl


  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bot
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - auth_info_baileys_back:/app/auth_info_baileys

volumes:
  portainer_data:
  auth_info_baileys_back:


