version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: "on-failure:5"
    ports:
      - "4242:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bot
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - auth_info_baileys_back:/app/auth_info_baileys

volumes:
  portainer_data:
  auth_info_baileys_back:


